"""
Shared PDF utilities for EduSphere reports.
Provides consistent layout, styling, and configuration across all PDF exports.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image
from datetime import datetime
import os


# Global variable to store generated time for footer
_footer_generated_time = None


def set_footer_generated_time(time_str):
    """Set the generated time for the footer."""
    global _footer_generated_time
    _footer_generated_time = time_str


def add_footer(canvas, doc):
    """Add standardized footer with page numbers and generated time."""
    global _footer_generated_time
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.grey)
    
    # Draw separator line
    canvas.setStrokeColor(colors.lightgrey)
    canvas.setLineWidth(0.5)
    canvas.line(35, 25, A4[0] - 35, 25)
    
    # Draw footer text
    page_num = canvas.getPageNumber()
    generated_time_str = _footer_generated_time if _footer_generated_time else datetime.now().strftime('%d %b %Y %H:%M')
    
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(
        A4[0] / 2,
        18,
        "Generated by EduSphere Examination System"
    )
    canvas.drawCentredString(
        A4[0] / 2,
        10,
        "This report is electronically generated and does not require a signature."
    )
    canvas.drawCentredString(
        A4[0] / 2,
        2,
        f"Generated by EduSphere Examination System | Page {page_num} | Generated on: {generated_time_str}"
    )
    
    canvas.restoreState()


def build_generic_report(title, summary, headers, rows, filename, landscape=False, logo_path=None):
    """
    Generic PDF builder function for all non-result reports.
    Produces output matching users.pdf exactly.
    
    Args:
        title: Report title (e.g., 'USERS REPORT')
        summary: List of [label, value] pairs for summary section
        headers: List of column headers
        rows: List of data rows (each row is a list of values)
        filename: Output filename
        landscape: Whether to use landscape orientation (default: False)
        logo_path: Optional path to logo image
    
    Returns:
        Flask Response object with PDF data
    """
    from flask import Response
    from io import BytesIO
    
    # Set footer generated time globally
    set_footer_generated_time(datetime.now().strftime('%d %b %Y %H:%M'))
    
    # Create PDF buffer with standard margins
    buffer = BytesIO()
    pagesize = A4
    if landscape:
        pagesize = (A4[1], A4[0])
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=pagesize,
        leftMargin=35,
        rightMargin=35,
        topMargin=40,
        bottomMargin=35,
        onFirstPage=add_footer,
        onLaterPages=add_footer
    )
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Normal style for body text
    normal_style = styles['Normal'].clone('normal')
    normal_style.fontSize = 10
    normal_style.leading = 12
    normal_style.textColor = colors.HexColor('#333333')
    normal_style.wordWrap = 'CJK'
    normal_style.splitLongWords = True
    
    # Title style
    title_style = styles['Normal'].clone('title')
    title_style.fontSize = 22
    title_style.fontName = 'Helvetica-Bold'
    title_style.textColor = colors.black
    title_style.leading = 26
    
    # Section header style
    section_style = styles['Normal'].clone('section')
    section_style.fontSize = 14
    section_style.fontName = 'Helvetica-Bold'
    section_style.textColor = colors.black
    section_style.leading = 18
    section_style.spaceBefore = 12
    section_style.spaceAfter = 8
    
    # Header text style (for EduSphere branding)
    header_style = styles['Normal'].clone('header')
    header_style.fontSize = 11
    header_style.fontName = 'Helvetica-Bold'
    header_style.textColor = colors.HexColor('#4F46E5')
    header_style.leading = 14
    
    # Subtitle style (for Examination System)
    subtitle_style = styles['Normal'].clone('subtitle')
    subtitle_style.fontSize = 9
    subtitle_style.fontName = 'Helvetica'
    subtitle_style.textColor = colors.grey
    subtitle_style.leading = 12
    
    elements = []
    
    # ===== HEADER =====
    # Centered title
    title_paragraph = Paragraph(title.upper(), title_style)
    
    # Right-aligned logo and branding
    if logo_path and os.path.exists(logo_path):
        logo = Image(logo_path, width=1.5*cm, height=1.5*cm)
        right_content = [
            Paragraph('EduSphere', header_style),
            Paragraph('Examination System', subtitle_style),
            logo
        ]
    else:
        right_content = [
            Paragraph('EduSphere', header_style),
            Paragraph('Examination System', subtitle_style)
        ]
    
    # Header table with centered title and right-aligned logo
    doc_width = 525  # Available width with 35pt margins
    header_data = [[title_paragraph, right_content]]
    header_table = Table(header_data, colWidths=[doc_width * 0.7, doc_width * 0.3])
    header_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
        ('LINEBELOW', (0, -1), (-1, -1), 0.5, colors.lightgrey),
    ]))
    elements.append(header_table)
    
    # ===== SUMMARY =====
    if summary:
        elements.append(Paragraph('SUMMARY', section_style))
        
        # Two-column table for summary items
        summary_data = []
        for label, value in summary:
            summary_data.append([
                Paragraph(f"<b>{label}:</b>", normal_style),
                Paragraph(str(value), normal_style)
            ])
        
        # Add generated timestamp
        summary_data.append([
            Paragraph(f"<b>Generated:</b>", normal_style),
            Paragraph(datetime.now().strftime('%d %b %Y %H:%M'), normal_style)
        ])
        
        summary_table = Table(summary_data, colWidths=[doc_width * 0.4, doc_width * 0.6])
        summary_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('GRID', (0, 0), (-1, -1), 0, colors.white),
        ]))
        elements.append(summary_table)
        
        # Spacer before table
        elements.append(Paragraph('', normal_style))
    
    # ===== TABLE =====
    # Calculate column widths as percentages of available width
    num_columns = len(headers)
    if num_columns > 0:
        col_widths = [doc_width / num_columns] * num_columns
    else:
        col_widths = []
    
    # Convert headers to Paragraph objects with word wrapping
    wrapped_headers = [Paragraph(str(h), normal_style) for h in headers]
    
    # Convert rows to Paragraph objects for text wrapping
    wrapped_rows = []
    for row in rows:
        wrapped_row = [Paragraph(str(cell) if cell else '', normal_style) for cell in row]
        wrapped_rows.append(wrapped_row)
    
    # Create table data
    table_data = [wrapped_headers] + wrapped_rows
    
    # Create table
    table = Table(table_data, colWidths=col_widths)
    table.setStyle(TableStyle([
        # Header styling
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4F46E5')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('LEFTPADDING', (0, 0), (-1, 0), 8),
        ('RIGHTPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        
        # Body styling
        ('LEFTPADDING', (0, 1), (-1, -1), 8),
        ('RIGHTPADDING', (0, 1), (-1, -1), 8),
        ('TOPPADDING', (0, 1), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.HexColor('#F7F9FC')]),
    ]))
    
    elements.append(table)
    
    # ===== FOOTER BLOCK =====
    elements.append(Paragraph('', normal_style))  # Spacer
    elements.append(Paragraph('Generated by EduSphere Examination System', normal_style))
    elements.append(Paragraph('This report is electronically generated and does not require a signature.', normal_style))
    
    # Build PDF
    doc.build(elements)
    
    # Create response
    buffer.seek(0)
    response = Response(buffer.getvalue(), mimetype='application/pdf')
    response.headers['Content-Disposition'] = f'attachment; filename={filename}'
    
    return response
