"""
Shared PDF utilities for EduSphere reports.
Provides consistent premium enterprise-quality layout, styling, and configuration across all PDF exports.
"""

from reportlab.lib.pagesizes import A4, landscape as landscape_pagesize
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image, Spacer
from datetime import datetime
import os


# Global variables for footer
_footer_generated_time = None
_footer_title = None
_page_number_callback = None


class PageNumberCallback:
    """Helper class to track page numbers for 'Page X of Y' footer."""
    def __init__(self):
        self.page_count = 0
    
    def increment(self):
        self.page_count += 1
    
    def get_total(self):
        return self.page_count


def set_footer_metadata(title, time_str):
    """Set the title and generated time for the footer."""
    global _footer_title, _footer_generated_time
    _footer_title = title
    _footer_generated_time = time_str


def add_page_footer(canvas, doc):
    """Add standardized page footer with separator, branding, page numbers, and timestamp."""
    global _footer_title, _footer_generated_time
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#777777'))
    
    pagesize = doc.pagesize
    width = pagesize[0]
    
    # Draw separator line
    canvas.setStrokeColor(colors.HexColor('#DDDDDD'))
    canvas.setLineWidth(0.8)
    canvas.line(35, 25, width - 35, 25)
    
    # Draw footer text
    page_num = canvas.getPageNumber()
    
    # Centered text
    canvas.drawCentredString(
        width / 2,
        18,
        "Generated by EduSphere Examination System"
    )
    canvas.drawCentredString(
        width / 2,
        10,
        "This report is electronically generated and does not require a signature."
    )
    
    # Bottom left - Generated On
    generated_date = datetime.now().strftime('%d %b %Y')
    generated_time = datetime.now().strftime('%I:%M %p')
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#777777'))
    canvas.drawString(
        35,
        18,
        f"Generated On: {generated_date}"
    )
    canvas.drawString(
        35,
        10,
        f"{generated_time}"
    )
    
    # Bottom right - Page X of Y (using doc.page for current, will need two-pass for total)
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#777777'))
    canvas.drawRightString(
        width - 35,
        14,
        f"Page {page_num}"
    )
    
    canvas.restoreState()


def get_styles():
    """Get all standard styles for the PDF template."""
    styles = getSampleStyleSheet()
    
    # Title style - centered, large bold
    title_style = styles['Normal'].clone('title')
    title_style.fontSize = 27
    title_style.fontName = 'Helvetica-Bold'
    title_style.textColor = colors.black
    title_style.leading = 33
    title_style.alignment = 1  # Center
    
    # Section header style
    section_style = styles['Normal'].clone('section')
    section_style.fontSize = 18
    section_style.fontName = 'Helvetica-Bold'
    section_style.textColor = colors.black
    section_style.leading = 22
    section_style.spaceBefore = 20
    section_style.spaceAfter = 14
    
    # Normal body text style
    normal_style = styles['Normal'].clone('normal')
    normal_style.fontSize = 10.5
    normal_style.leading = 13
    normal_style.textColor = colors.HexColor('#333333')
    normal_style.wordWrap = 'CJK'
    normal_style.splitLongWords = True
    
    # Summary label style (bold)
    summary_label_style = styles['Normal'].clone('summary_label')
    summary_label_style.fontSize = 11
    summary_label_style.fontName = 'Helvetica-Bold'
    summary_label_style.textColor = colors.black
    summary_label_style.leading = 14
    
    # Summary value style (regular)
    summary_value_style = styles['Normal'].clone('summary_value')
    summary_value_style.fontSize = 11
    summary_value_style.fontName = 'Helvetica'
    summary_value_style.textColor = colors.black
    summary_value_style.leading = 14
    
    # Header branding style (EduSphere)
    header_brand_style = styles['Normal'].clone('header_brand')
    header_brand_style.fontSize = 12
    header_brand_style.fontName = 'Helvetica-Bold'
    header_brand_style.textColor = colors.HexColor('#4338CA')
    header_brand_style.leading = 14
    header_brand_style.alignment = 1  # Center
    
    # Header subtitle style (Examination System)
    header_subtitle_style = styles['Normal'].clone('header_subtitle')
    header_subtitle_style.fontSize = 10
    header_subtitle_style.fontName = 'Helvetica'
    header_subtitle_style.textColor = colors.grey
    header_subtitle_style.leading = 12
    header_subtitle_style.alignment = 1  # Center
    
    # Footer text style
    footer_style = styles['Normal'].clone('footer')
    footer_style.fontSize = 9
    footer_style.fontName = 'Helvetica'
    footer_style.textColor = colors.HexColor('#777777')
    footer_style.leading = 12
    footer_style.alignment = 1  # Center
    
    # Empty table message style
    empty_style = styles['Normal'].clone('empty')
    empty_style.fontSize = 11
    empty_style.fontName = 'Helvetica-Oblique'
    empty_style.textColor = colors.grey
    empty_style.leading = 14
    empty_style.alignment = 1  # Center
    
    return {
        'title': title_style,
        'section': section_style,
        'normal': normal_style,
        'summary_label': summary_label_style,
        'summary_value': summary_value_style,
        'header_brand': header_brand_style,
        'header_subtitle': header_subtitle_style,
        'footer': footer_style,
        'empty': empty_style
    }


def create_report_header(title, logo_path, doc_width):
    """
    Create the report header with centered title and right-aligned logo.
    
    Args:
        title: Report title (e.g., 'USERS REPORT')
        logo_path: Path to logo image (optional)
        doc_width: Available document width
    
    Returns:
        Table object for the header
    """
    styles = get_styles()
    
    # Centered title paragraph
    title_paragraph = Paragraph(title.upper(), styles['title'])
    
    # Right-aligned logo and branding
    if logo_path and os.path.exists(logo_path):
        # Logo 40-50% larger (2.1cm instead of 1.5cm)
        logo = Image(logo_path, width=2.1*cm, height=2.1*cm)
        right_content = [
            Paragraph('EduSphere', styles['header_brand']),
            Paragraph('Examination System', styles['header_subtitle']),
            logo
        ]
    else:
        right_content = [
            Paragraph('EduSphere', styles['header_brand']),
            Paragraph('Examination System', styles['header_subtitle'])
        ]
    
    # Header table with centered title and right-aligned logo
    header_data = [[title_paragraph, right_content]]
    header_table = Table(header_data, colWidths=[doc_width * 0.65, doc_width * 0.35])
    header_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 25),
        ('LINEBELOW', (0, -1), (-1, -1), 0.8, colors.HexColor('#DDDDDD')),
    ]))
    
    return header_table


def create_summary_section(summary, doc_width):
    """
    Create the summary section with non-table layout.
    
    Args:
        summary: List of [label, value] pairs
        doc_width: Available document width
    
    Returns:
        List of flowables for the summary section
    """
    styles = get_styles()
    elements = []
    
    # Summary heading
    elements.append(Paragraph('SUMMARY', styles['section']))
    
    # Summary items as paragraphs with consistent spacing
    for label, value in summary:
        # Create a table for each row to ensure alignment
        row_data = [
            [Paragraph(f"<b>{label}</b>", styles['summary_label']), 
             Paragraph(str(value), styles['summary_value'])]
        ]
        row_table = Table(row_data, colWidths=[doc_width * 0.5, doc_width * 0.5])
        row_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 2),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
            ('GRID', (0, 0), (-1, -1), 0, colors.white),
        ]))
        elements.append(row_table)
    
    # Add generated timestamp
    generated_date = datetime.now().strftime('%d %b %Y')
    generated_time = datetime.now().strftime('%I:%M %p')
    
    for label, value in [('Generated On', generated_date), ('Generated Time', generated_time)]:
        row_data = [
            [Paragraph(f"<b>{label}</b>", styles['summary_label']), 
             Paragraph(str(value), styles['summary_value'])]
        ]
        row_table = Table(row_data, colWidths=[doc_width * 0.5, doc_width * 0.5])
        row_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 2),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
            ('GRID', (0, 0), (-1, -1), 0, colors.white),
        ]))
        elements.append(row_table)
    
    # Spacer before table
    elements.append(Spacer(1, 18))
    
    return elements


def get_column_alignment(header_name):
    """
    Determine appropriate alignment based on column header name.
    
    Args:
        header_name: The column header string
    
    Returns:
        Alignment string ('LEFT', 'CENTER', or 'RIGHT')
    """
    header_lower = header_name.lower()
    
    # Center-align these columns
    center_columns = ['status', 'role', 'score', 'total', '%', 'result', 'percentage', 
                      'date', 'time', 'attempts', 'avg', 'max', 'min', 'count', 'id']
    
    # Right-align numeric columns
    right_columns = ['amount', 'price', 'cost', 'value']
    
    for col in center_columns:
        if col in header_lower:
            return 'CENTER'
    
    for col in right_columns:
        if col in header_lower:
            return 'RIGHT'
    
    # Default to left for names, emails, descriptions
    return 'LEFT'


def create_standard_table(headers, rows, doc_width):
    """
    Create a modern table with zebra rows, auto-alignment, and text wrapping.
    
    Args:
        headers: List of column headers
        rows: List of data rows
        doc_width: Available document width
    
    Returns:
        Table object or empty message paragraph
    """
    styles = get_styles()
    
    # Handle empty table
    if not rows or len(rows) == 0:
        return Paragraph('No records available.', styles['empty'])
    
    # Calculate column widths as percentages of available width
    num_columns = len(headers)
    if num_columns > 0:
        col_widths = [doc_width / num_columns] * num_columns
    else:
        col_widths = []
    
    # Convert headers to Paragraph objects with word wrapping (never wrap headers)
    wrapped_headers = []
    for h in headers:
        p = Paragraph(str(h), styles['normal'])
        p.style.alignment = 1  # Center headers
        wrapped_headers.append(p)
    
    # Convert rows to Paragraph objects for text wrapping with auto-alignment
    wrapped_rows = []
    for row in rows:
        wrapped_row = []
        for idx, cell in enumerate(row):
            header_name = headers[idx] if idx < len(headers) else ''
            alignment = get_column_alignment(header_name)
            p = Paragraph(str(cell) if cell else '', styles['normal'])
            p.style.alignment = 0 if alignment == 'LEFT' else (1 if alignment == 'CENTER' else 2)
            wrapped_row.append(p)
        wrapped_rows.append(wrapped_row)
    
    # Create table data
    table_data = [wrapped_headers] + wrapped_rows
    
    # Create table
    table = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    # Build table style with zebra rows
    table_style = TableStyle([
        # Header styling - purple background, white bold text
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4338CA')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('VALIGN', (0, 0), (-1, 0), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, 0), 10),
        ('RIGHTPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        
        # Body styling - minimum row height 28pt, zebra rows
        ('LEFTPADDING', (0, 1), (-1, -1), 10),
        ('RIGHTPADDING', (0, 1), (-1, -1), 10),
        ('TOPPADDING', (0, 1), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 12),
        ('VALIGN', (0, 1), (-1, -1), 'MIDDLE'),
        ('MINROWHEIGHT', (0, 1), (-1, -1), 28),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DDDDDD')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8F9FA')]),
    ])
    
    # Apply per-column alignment for body rows
    for col_idx, header in enumerate(headers):
        alignment = get_column_alignment(header)
        table_style.add('ALIGN', (col_idx, 1), (col_idx, -1), alignment)
    
    table.setStyle(table_style)
    
    return table


def create_footer():
    """
    Create the footer block that appears after the table.
    
    Returns:
        List of flowables for the footer
    """
    styles = get_styles()
    elements = []
    
    elements.append(Spacer(1, 30))
    elements.append(Paragraph('Generated by EduSphere Examination System', styles['footer']))
    elements.append(Paragraph('This report is electronically generated and does not require a signature.', styles['footer']))
    
    return elements


def should_use_landscape(headers):
    """
    Determine if landscape orientation should be used based on column count.
    
    Args:
        headers: List of column headers
    
    Returns:
        Boolean indicating whether to use landscape
    """
    # Use landscape if more than 6 columns
    return len(headers) > 6


def build_premium_report(title, summary, headers, rows, filename, logo_path=None):
    """
    Premium PDF builder function for all non-result reports.
    Produces enterprise-quality output with consistent design across all reports.
    
    Args:
        title: Report title (e.g., 'USERS REPORT')
        summary: List of [label, value] pairs for summary section
        headers: List of column headers
        rows: List of data rows (each row is a list of values)
        filename: Output filename
        logo_path: Optional path to logo image
    
    Returns:
        Flask Response object with PDF data
    """
    from flask import Response
    from io import BytesIO
    
    # Set footer metadata globally
    generated_time = datetime.now().strftime('%d %b %Y %I:%M %p')
    set_footer_metadata(title, generated_time)
    
    # Auto-detect landscape orientation
    use_landscape = should_use_landscape(headers)
    
    # Create PDF buffer with standard margins
    buffer = BytesIO()
    pagesize = landscape_pagesize(A4) if use_landscape else A4
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=pagesize,
        leftMargin=35,
        rightMargin=35,
        topMargin=30,
        bottomMargin=40,
        onFirstPage=add_page_footer,
        onLaterPages=add_page_footer
    )
    
    # Calculate available document width
    doc_width = pagesize[0] - 70  # Subtract margins
    
    # Get styles
    styles = get_styles()
    
    # Build elements list
    elements = []
    
    # ===== HEADER =====
    elements.append(create_report_header(title, logo_path, doc_width))
    elements.append(Spacer(1, 15))
    
    # ===== SUMMARY =====
    if summary:
        elements.extend(create_summary_section(summary, doc_width))
    
    # ===== TABLE =====
    elements.append(create_standard_table(headers, rows, doc_width))
    
    # Build PDF
    doc.build(elements)
    
    # Create response
    buffer.seek(0)
    response = Response(buffer.getvalue(), mimetype='application/pdf')
    response.headers['Content-Disposition'] = f'attachment; filename={filename}'
    
    return response
